
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '21C9D6EFC81EB4876511F1202CB74E2F'
    
_lr_action_items = {'DRAW':([7,13,],[-16,20,]),'ELLIPSE':([0,],[11,]),'END':([0,],[3,]),'POLYGON':([0,],[4,]),'TEXT':([0,],[6,]),'NUMBER':([4,5,6,7,15,16,17,18,19,22,23,25,26,27,28,29,31,32,33,38,39,40,45,53,54,58,59,63,64,68,69,73,74,78,],[14,15,16,-16,23,24,25,26,27,28,29,31,32,33,34,35,37,38,39,43,44,45,50,54,56,59,61,64,66,69,71,74,76,79,]),'ID':([0,1,7,9,11,12,24,35,37,41,42,43,44,48,49,54,55,59,60,64,65,69,70,74,75,79,80,],[7,7,-16,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,]),'CREATEHTML':([0,],[8,]),'CIRCLE':([0,],[9,]),'MOVERIGHT':([7,13,],[-16,21,]),'COMA':([14,34,50,56,61,66,71,76,],[22,40,53,58,63,68,73,78,]),'STRINGVALUE':([7,30,],[-16,36,]),'ANIMATE':([0,],[1,]),'LINE':([0,],[5,]),'RECT':([0,],[12,]),'$end':([2,3,7,8,10,20,21,36,46,47,51,52,57,62,67,72,77,81,],[-17,-13,-16,-1,0,-14,-15,-12,-5,-2,-4,-3,-6,-7,-8,-9,-10,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,1,9,11,12,24,35,37,41,42,43,44,48,49,54,55,59,60,64,65,69,70,74,75,79,80,],[2,13,17,18,19,30,41,42,46,47,48,49,51,52,55,57,60,62,65,67,70,72,75,77,80,81,]),'expression':([0,],[10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> CREATEHTML','expression',1,'p_expression_createhtml','Parser.py',18),
  ('expression -> CIRCLE term NUMBER NUMBER NUMBER term term','expression',7,'p_expression_circle','Parser.py',25),
  ('expression -> RECT term NUMBER NUMBER NUMBER NUMBER term term','expression',8,'p_expression_rectangle','Parser.py',32),
  ('expression -> ELLIPSE term NUMBER NUMBER NUMBER NUMBER term term','expression',8,'p_expression_ellipse','Parser.py',38),
  ('expression -> LINE NUMBER NUMBER NUMBER NUMBER term term','expression',7,'p_expression_line','Parser.py',44),
  ('expression -> POLYGON NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER term term','expression',12,'p_expression_polygon','Parser.py',50),
  ('expression -> POLYGON NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER term term','expression',15,'p_expression_polygon','Parser.py',51),
  ('expression -> POLYGON NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER term term','expression',18,'p_expression_polygon','Parser.py',52),
  ('expression -> POLYGON NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER term term','expression',21,'p_expression_polygon','Parser.py',53),
  ('expression -> POLYGON NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER term term','expression',24,'p_expression_polygon','Parser.py',54),
  ('expression -> POLYGON NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER NUMBER COMA NUMBER term term','expression',27,'p_expression_polygon','Parser.py',55),
  ('expression -> TEXT NUMBER NUMBER term STRINGVALUE','expression',5,'p_expression_text','Parser.py',71),
  ('expression -> END','expression',1,'p_expression_end','Parser.py',77),
  ('expression -> ANIMATE term DRAW','expression',3,'p_animate_draw','Parser.py',83),
  ('expression -> ANIMATE term MOVERIGHT','expression',3,'p_animate_moveright','Parser.py',88),
  ('term -> ID','term',1,'p_term_ID','Parser.py',99),
  ('expression -> term','expression',1,'p_expression_term','Parser.py',107),
]
